spring.application.name=delta_api_mongo

delta.mongodb.telemetry.uri=${MONGODB_TELEMETRY_URI}
delta.mongodb.telemetry.database=${MONGODB_TELEMETRY_DATABASE:db_delta_telemetry}

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
